// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// pgal
Rcpp::List pgal(arma::mat Phi1, arma::mat Phi2, arma::mat Phi3, arma::mat Y, arma::mat Weights, std::string family, std::string iwls, double nu, arma::vec lambda, int makelamb, int nlambda, double lambdaminratio, arma::mat penaltyfactor, double reltolprox, double reltolnewt, int maxiter, int maxiterprox, int maxiternewt, int btproxmax, int weightedgaussian);
RcppExport SEXP glamlasso_pgal(SEXP Phi1SEXP, SEXP Phi2SEXP, SEXP Phi3SEXP, SEXP YSEXP, SEXP WeightsSEXP, SEXP familySEXP, SEXP iwlsSEXP, SEXP nuSEXP, SEXP lambdaSEXP, SEXP makelambSEXP, SEXP nlambdaSEXP, SEXP lambdaminratioSEXP, SEXP penaltyfactorSEXP, SEXP reltolproxSEXP, SEXP reltolnewtSEXP, SEXP maxiterSEXP, SEXP maxiterproxSEXP, SEXP maxiternewtSEXP, SEXP btproxmaxSEXP, SEXP weightedgaussianSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Phi1(Phi1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi2(Phi2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi3(Phi3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Weights(WeightsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< std::string >::type iwls(iwlsSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type makelamb(makelambSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambdaminratio(lambdaminratioSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type penaltyfactor(penaltyfactorSEXP);
    Rcpp::traits::input_parameter< double >::type reltolprox(reltolproxSEXP);
    Rcpp::traits::input_parameter< double >::type reltolnewt(reltolnewtSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterprox(maxiterproxSEXP);
    Rcpp::traits::input_parameter< int >::type maxiternewt(maxiternewtSEXP);
    Rcpp::traits::input_parameter< int >::type btproxmax(btproxmaxSEXP);
    Rcpp::traits::input_parameter< int >::type weightedgaussian(weightedgaussianSEXP);
    __result = Rcpp::wrap(pgal(Phi1, Phi2, Phi3, Y, Weights, family, iwls, nu, lambda, makelamb, nlambda, lambdaminratio, penaltyfactor, reltolprox, reltolnewt, maxiter, maxiterprox, maxiternewt, btproxmax, weightedgaussian));
    return __result;
END_RCPP
}
// getobj
Rcpp::List getobj(arma::mat Y, arma::mat Weights, arma::mat Phi1, arma::mat Phi2, arma::mat Phi3, Rcpp::NumericVector beta, arma::vec lambda, arma::mat penaltyfactor, std::string family);
RcppExport SEXP glamlasso_getobj(SEXP YSEXP, SEXP WeightsSEXP, SEXP Phi1SEXP, SEXP Phi2SEXP, SEXP Phi3SEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP penaltyfactorSEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Weights(WeightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi1(Phi1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi2(Phi2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi3(Phi3SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type penaltyfactor(penaltyfactorSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    __result = Rcpp::wrap(getobj(Y, Weights, Phi1, Phi2, Phi3, beta, lambda, penaltyfactor, family));
    return __result;
END_RCPP
}
