# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gdpg <- function(Phi1, Phi2, Phi3, Y, Weights, family, penalty, iwls, nu, lambda, makelamb, nlambda, lambdaminratio, penaltyfactor, reltolprox, reltolnewt, maxiter, steps, maxiterprox, maxiternewt, btproxmax, weightedgaussian) {
    .Call('glamlasso_gdpg', PACKAGE = 'glamlasso', Phi1, Phi2, Phi3, Y, Weights, family, penalty, iwls, nu, lambda, makelamb, nlambda, lambdaminratio, penaltyfactor, reltolprox, reltolnewt, maxiter, steps, maxiterprox, maxiternewt, btproxmax, weightedgaussian)
}

getobj <- function(Y, Weights, Phi1, Phi2, Phi3, beta, lambda, penaltyfactor, family, penalty) {
    .Call('glamlasso_getobj', PACKAGE = 'glamlasso', Y, Weights, Phi1, Phi2, Phi3, beta, lambda, penaltyfactor, family, penalty)
}

